### PR TITLE
fix anonymous walk deprecation

### LINKED ISSUE #124: use structs instead of functions for walks in destructure
Starting julia with `julia --depwarn=yes` we get
```julia
julia> using Flux, Optimisers

julia> nn = Chain(
           Dense(1 => 3, tanh),
           Dense(3 => 1, tanh),
       );

julia> Optimisers.destructure(nn)
┌ Warning: Wrapping a custom walk function as an `AnonymousWalk`. Future versions will only support custom walks that explicitly subtype `AbstractWalk`.
│   caller = #fmap#27 at maps.jl:7 [inlined]
└ @ Core ~/.julia/packages/Functors/dFhrk/src/maps.jl:7
(Float32[-0.9446188, -0.1429313, -0.7826553, 0.0, 0.0, 0.0, -1.0964488, 0.8614038, -1.2199631, 0.0], Restructure(Chain, ..., 10))

julia> Optimisers.destructure(nn)
```
We should rewrite those closures into structs. 
Reported in https://github.com/FluxML/Functors.jl/issues/60.

### PR DESCRIPTION
**Pull request by CarloLucibello**
Fix #124

### CODE REVIEW

File: src/destructure.jl [hunk 1]
```diff
@@ -61,12 +61,16 @@ end
 Base.show(io::IO, re::Restructure{T}) where T = print(io, "Restructure(", T.name.name, ", ..., ", re.length, ")")
 Base.length(re::Restructure) = re.length
 
+
+struct _FlattenWalk <: AbstractWalk end
+(::_FlattenWalk)(recurse, x) = map(recurse, _trainable(x))
```
Comment (mcabbott) [inline src/destructure.jl:66]: I think this ought to be called `_TrainableStructWalk`, it doesn't flatten, just happens to be used there.

I also think that for this file's style, it ought to be defined just below `_flatten(x)`.

**Review by ToucheSir — APPROVED** [review]
Failure on nightly is due to Yota and not anything in this package.
