### PR TITLE
fix AdamW

### LINKED ISSUE #197: AdamW: epsilon and lambda swapped?
image

Weird, given that the docs imply epsilon is non-zero:

image

But looking at the code, the field order in the struct vs the constructors seems to swap them?

image

### PR DESCRIPTION
**Pull request by CarloLucibello**
fix #197

### CODE REVIEW

**Review by ToucheSir — APPROVED** [review]

File: src/rules.jl [hunk 1]
```diff
@@ -538,7 +538,7 @@ end
 
 function AdamW(η, β = (0.9, 0.999), λ = 0.0, ϵ = 1e-8; couple::Bool = true)
```
Comment (mcabbott) [inline src/rules.jl:539]: One method puts epsilon 3rd, and one puts it 4th. Shouldn't these orders always agree?

Comment (mcabbott) [reply src/rules.jl:539]: (That was supposed to highlight the struct definition, too.)

Also, why does this allow any types, not Float64 like other rules?

Comment (CarloLucibello) [reply src/rules.jl]: I would allow for at least `AdamW(eta; couple=true)` so 
> Or we could elaborate the macro to always allow n positional and N-n keywords for the remaining arguments.

seems a viable option that preserves all current construction modalities, right?

Comment (mcabbott) [reply src/rules.jl]: Yes.

For now at least fix the types?

Comment (CarloLucibello) [reply src/rules.jl]: Ok
