### PR TITLE
Use `eltype(x)` everywhere, ignore `typeof(η)`

### LINKED ISSUE #119: Adam(0) fails
### Package Version

0.2.10

### Julia Version

1.8.3

### OS / Environment

Linux

### Describe the bug

Cannot create rule (e.g. `Adam`) with integer learning rate.

### Steps to Reproduce

```
julia> Adam(0) # any integer learning rate
```

### Expected Results

`Adam(0.0)` works fine. I believe `Adam(0)` should behave like `Adam(0.0)`.

### Observed Results

```
ERROR: MethodError: no method matching eps(::Type{Int64})
Closest candidates are:
  eps() at float.jl:831
  eps(::AbstractFloat) at float.jl:827
  eps(::T) where T<:Dates.TimeType at ~/.julia/juliaup/julia-1.8.3+0.x64/share/julia/stdlib/v1.8/Dates/src/types.jl:444
  ...
Stacktrace:
 [1] Adam(η::Int64)
   @ Optimisers ~/.julia/packages/Optimisers/GKFy2/src/rules.jl:205
 [2] top-level scope
   @ REPL[28]:1
```

### Relevant log output

_No response_

### LINKED ISSUE #150: Error in `update!` for Metal arrays and Adam optimiser
The following lines using `Descent` run fine
```julia
julia> using Optimisers, Flux

julia> x = rand(Float32, 3) |> Flux.gpu
3-element MtlVector{Float32, Metal.MTL.MTLResourceStorageModePrivate}:
 0.6247813
 0.75746953
 0.9677551

julia> g = rand(Float32, 3) |> Flux.gpu
3-element MtlVector{Float32, Metal.MTL.MTLResourceStorageModePrivate}:
 0.22261995
 0.24903625
 0.07521629

julia> opt = Optimisers.setup(Optimisers.Descent(1e-3), x)
Leaf(Descent{Float64}(0.001), nothing)

julia> Optimisers.update!(opt, x, g) # OK
(Leaf(Descent{Float64}(0.001), nothing), Float32[0.6245587, 0.7572205, 0.96767986])
```
Now with `Adam` instead:
```julia
julia> opt = Optimisers.setup(Optimisers.Adam(1e-3), x)
Leaf(Adam{Float64}(0.001, (0.9, 0.999), 2.22045e-16), (Float32[0.0, 0.0, 0.0], Float32[0.0, 0.0, 0.0], (0.9, 0.999)))

julia> Optimisers.update!(opt, model, g)
ERROR: InvalidIRError: compiling MethodInstance for (::GPUArrays.var"#broadcast_kernel#26")(::Metal.mtlKernelContext, ::MtlDeviceVector{Float32, 1}, ::Base.Broadcast.Broadcasted{Metal.MtlArrayStyle{1}, Tuple{Base.OneTo{Int64}}, typeof(+), Tuple{Base.Broadcast.Broadcasted{Metal.MtlArrayStyle{1}, Nothing, typeof(*), Tuple{Float64, Base.Broadcast.Extruded{MtlDeviceVector{Float32, 1}, Tuple{Bool}, Tuple{Int64}}}}, Base.Broadcast.Broadcasted{Metal.MtlArrayStyle{1}, Nothing, typeof(*), Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{0}, Nothing, typeof(-), Tuple{Int64, Float64}}, Base.Broadcast.Extruded{MtlDeviceVector{Float32, 1}, Tuple{Bool}, Tuple{Int64}}}}}}, ::Int64) resulted in invalid LLVM IR
Reason: unsupported unsupported use of double value
Reason: unsupported unsupported use of double value
Reason: unsupported unsupported use of double value
Reason: unsupported unsupported use of double value
Reason: unsupported unsupported use of double value
Stacktrace:
  [1] Float64
    @ ./float.jl:261
  [2] convert
    @ ./number.jl:7
  [3] _promote
    @ ./promotion.jl:358
  [4] promote
    @ ./promotion.jl:381
  [5] *
    @ ./promotion.jl:411
  [6] _broadcast_getindex_evalf
    @ ./broadcast.jl:683
  [7] _broadcast_getindex
    @ ./broadcast.jl:656
  [8] _getindex
    @ ./broadcast.jl:679
  [9] _broadcast_getindex
    @ ./broadcast.jl:655
 [10] getindex
    @ ./broadcast.jl:610
 [11] broadcast_kernel
    @ ~/.julia/packages/GPUArrays/5XhED/src/host/broadcast.jl:59
Reason: unsupported unsupported use of double value
...
Stacktrace:
 [1] Float32
   @ ./float.jl:258
 [2] convert
   @ ./number.jl:7
 [3] setindex!
   @ ~/.julia/packages/Metal/qeZqc/src/device/array.jl:105
 [4] setindex!
   @ ~/.julia/packages/Metal/qeZqc/src/device/array.jl:118
 [5] broadcast_kernel
   @ ~/.julia/packages/GPUArrays/5XhED/src/host/broadcast.jl:59
Hint: catch this exception as `err` and call `code_typed(err; interactive = true)` to introspect the erronous code with Cthulhu.jl
Stacktrace:
  [1] check_ir(job::GPUCompiler.CompilerJob{GPUCompiler.MetalCompilerTarget, Metal.MetalCompilerParams}, args::LLVM.Module)
    @ GPUCompiler ~/.julia/packages/GPUCompiler/YO8Uj/src/validation.jl:149
  [2] macro expansion
    @ ~/.julia/packages/GPUCompiler/YO8Uj/src/driver.jl:415 [inlined]
  [3] macro expansion
    @ ~/.julia/packages/TimerOutputs/RsWnF/src/TimerOutput.jl:253 [inlined]
  [4] macro expansion
    @ ~/.julia/packages/GPUCompiler/YO8Uj/src/driver.jl:414 [inlined]
  [5] emit_llvm(job::GPUCompiler.CompilerJob; libraries::Bool, toplevel::Bool, optimize::Bool, cleanup::Bool, only_entry::Bool, validate::Bool)
    @ GPUCompiler ~/.julia/packages/GPUCompiler/YO8Uj/src/utils.jl:89
  [6] emit_llvm
    @ ~/.julia/packages/GPUCompiler/YO8Uj/src/utils.jl:83 [inlined]
  [7] codegen(output::Symbol, job::GPUCompiler.CompilerJob; libraries::Bool, toplevel::Bool, optimize::Bool, cleanup::Bool, strip::Bool, validate::Bool, only_entry::Bool, parent_job::Nothing)
    @ GPUCompiler ~/.julia/packages/GPUCompiler/YO8Uj/src/driver.jl:129
  [8] codegen
    @ ~/.julia/packages/GPUCompiler/YO8Uj/src/driver.jl:110 [inlined]
  [9] compile(target::Symbol, job::GPUCompiler.CompilerJob; libraries::Bool, toplevel::Bool, optimize::Bool, cleanup::Bool, strip::Bool, validate::Bool, only_entry::Bool)
    @ GPUCompiler ~/.julia/packages/GPUCompiler/YO8Uj/src/driver.jl:106
 [10] compile
    @ ~/.julia/packages/GPUCompiler/YO8Uj/src/driver.jl:98 [inlined]
 [11] #51
    @ ~/.julia/packages/Metal/qeZqc/src/compiler/compilation.jl:57 [inlined]
 [12] JuliaContext(f::Metal.var"#51#52"{GPUCompiler.CompilerJob{GPUCompiler.MetalCompilerTarget, Metal.MetalCompilerParams}})
    @ GPUCompiler ~/.julia/packages/GPUCompiler/YO8Uj/src/driver.jl:47
 [13] compile(job::GPUCompiler.CompilerJob)
    @ Metal ~/.julia/packages/Metal/qeZqc/src/compiler/compilation.jl:56
 [14] actual_compilation(cache::Dict{Any, Any}, src::Core.MethodInstance, world::UInt64, cfg::GPUCompiler.CompilerConfig{GPUCompiler.MetalCompilerTarget, Metal.MetalCompilerParams}, compiler::typeof(Metal.compile), linker::typeof(Metal.link))
    @ GPUCompiler ~/.julia/packages/GPUCompiler/YO8Uj/src/execution.jl:125
 [15] cached_compilation(cache::Dict{Any, Any}, src::Core.MethodInstance, cfg::GPUCompiler.CompilerConfig{GPUCompiler.MetalCompilerTarget, Metal.MetalCompilerParams}, compiler::Function, linker::Function)
    @ GPUCompiler ~/.julia/packages/GPUCompiler/YO8Uj/src/execution.jl:103
 [16] macro expansion
    @ ~/.julia/packages/Metal/qeZqc/src/compiler/execution.jl:162 [inlined]
 [17] macro expansion
    @ ./lock.jl:267 [inlined]
 [18] mtlfunction(f::GPUArrays.var"#broadcast_kernel#26", tt::Type{Tuple{Metal.mtlKernelContext, MtlDeviceVector{Float32, 1}, Base.Broadcast.Broadcasted{Metal.MtlArrayStyle{1}, Tuple{Base.OneTo{Int64}}, typeof(+), Tuple{Base.Broadcast.Broadcasted{Metal.MtlArrayStyle{1}, Nothing, typeof(*), Tuple{Float64, Base.Broadcast.Extruded{MtlDeviceVector{Float32, 1}, Tuple{Bool}, Tuple{Int64}}}}, Base.Broadcast.Broadcasted{Metal.MtlArrayStyle{1}, Nothing, typeof(*), Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{0}, Nothing, typeof(-), Tuple{Int64, Float64}}, Base.Broadcast.Extruded{MtlDeviceVector{Float32, 1}, Tuple{Bool}, Tuple{Int64}}}}}}, Int64}}; name::Nothing, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Metal ~/.julia/packages/Metal/qeZqc/src/compiler/execution.jl:157
 [19] mtlfunction(f::GPUArrays.var"#broadcast_kernel#26", tt::Type{Tuple{Metal.mtlKernelContext, MtlDeviceVector{Float32, 1}, Base.Broadcast.Broadcasted{Metal.MtlArrayStyle{1}, Tuple{Base.OneTo{Int64}}, typeof(+), Tuple{Base.Broadcast.Broadcasted{Metal.MtlArrayStyle{1}, Nothing, typeof(*), Tuple{Float64, Base.Broadcast.Extruded{MtlDeviceVector{Float32, 1}, Tuple{Bool}, Tuple{Int64}}}}, Base.Broadcast.Broadcasted{Metal.MtlArrayStyle{1}, Nothing, typeof(*), Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{0}, Nothing, typeof(-), Tuple{Int64, Float64}}, Base.Broadcast.Extruded{MtlDeviceVector{Float32, 1}, Tuple{Bool}, Tuple{Int64}}}}}}, Int64}})
    @ Metal ~/.julia/packages/Metal/qeZqc/src/compiler/execution.jl:155
 [20] macro expansion
    @ ~/.julia/packages/Metal/qeZqc/src/compiler/execution.jl:77 [inlined]
 [21] #launch_heuristic#98
    @ ~/.julia/packages/Metal/qeZqc/src/gpuarrays.jl:14 [inlined]
 [22] launch_heuristic
    @ ~/.julia/packages/Metal/qeZqc/src/gpuarrays.jl:12 [inlined]
 [23] _copyto!
    @ ~/.julia/packages/GPUArrays/5XhED/src/host/broadcast.jl:65 [inlined]
 [24] materialize!
    @ ~/.julia/packages/GPUArrays/5XhED/src/host/broadcast.jl:41 [inlined]
 [25] materialize!
    @ ./broadcast.jl:881 [inlined]
 [26] macro expansion
    @ ~/.julia/packages/Optimisers/1x8gl/src/interface.jl:201 [inlined]
 [27] apply!(o::Optimisers.Adam{Float64}, state::Tuple{MtlVector{Float32, Metal.MTL.MTLResourceStorageModePrivate}, MtlVector{Float32, Metal.MTL.MTLResourceStorageModePrivate}, Tuple{Float64, Float64}}, x::MtlVector{Float32, Metal.MTL.MTLResourceStorageModePrivate}, dx::MtlVector{Float32, Metal.MTL.MTLResourceStorageModePrivate})
    @ Optimisers ~/.julia/packages/Optimisers/1x8gl/src/rules.jl:213
 [28] _update!(ℓ::Optimisers.Leaf{Optimisers.Adam{Float64}, Tuple{MtlVector{Float32, Metal.MTL.MTLResourceStorageModePrivate}, MtlVector{Float32, Metal.MTL.MTLResourceStorageModePrivate}, Tuple{Float64, Float64}}}, x::MtlVector{Float32, Metal.MTL.MTLResourceStorageModePrivate}; grads::IdDict{Optimisers.Leaf, Any}, params::IdDict{Any, Any})
    @ Optimisers ~/.julia/packages/Optimisers/1x8gl/src/interface.jl:92
 [29] _update!
    @ ~/.julia/packages/Optimisers/1x8gl/src/interface.jl:88 [inlined]
 [30] update!(::Optimisers.Leaf{Optimisers.Adam{Float64}, Tuple{MtlVector{Float32, Metal.MTL.MTLResourceStorageModePrivate}, MtlVector{Float32, Metal.MTL.MTLResourceStorageModePrivate}, Tuple{Float64, Float64}}}, ::MtlVector{Float32, Metal.MTL.MTLResourceStorageModePrivate}, ::MtlVector{Float32, Metal.MTL.MTLResourceStorageModePrivate})
    @ Optimisers ~/.julia/packages/Optimisers/1x8gl/src/interface.jl:73
 [31] top-level scope
    @ REPL[31]:1
```

### PR DESCRIPTION
**Pull request by mcabbott**
First commit should fix #150, by working all in Float32. ~~Chooses to do this by always following the momentum from `setup`, not the `x`, but perhaps that's messy?~~ changed to `eltype(x)` now.

Since the type of `η` is now ignored, perhaps we should just remove all the type parameters? Then e.g. `Adam(0) == Adam(0.0)`, fixes #119, closes #120. Also closes #86 (redundant). 

~~Not all rules are changed yet, RFC?~~

### CODE REVIEW

**Comment by CarloLucibello** [comment]
> we should just remove all the type parameters?

definitely, we also get nicer prints of the opt_state has a bonus

**Comment by ToucheSir** [comment]
If using the eltype of momentum is too restrictive, we could always change to some promoted eltype of various parts of input + state (e.g. momentum + param + gradient eltypes). Otherwise 👍 from me though, nice to see that this works!

File: src/rules.jl [hunk 1]
```diff
@@ -40,23 +40,24 @@ Gradient descent optimizer with learning rate `η` and momentum `ρ`.
...
 end
-Momentum(η = 1f-2, ρ = 9f-1) = Momentum{typeof(η)}(η, ρ)
 
 init(o::Momentum, x::AbstractArray) = zero(x)
 
-function apply!(o::Momentum, state, x, dx)
-  η, ρ, mvel = o.eta, o.rho, state
+function apply!(o::Momentum, mvel, x, dx)
+  T = eltype(mvel)
+  η, ρ = T(o.eta), T(o.rho)
```
Comment (mcabbott) [inline src/rules.jl:53]: The downside of using `T = eltype(momentum)` is that you have to unpack the momentum first, while many rules are written either (as here) to unpack state and hyper-parameters at once, or else to unpack momentum later.

Maybe using `eltype(x)` would also be fine, and simpler?

File: src/rules.jl [hunk 2]
```diff
@@ -40,23 +40,24 @@ Gradient descent optimizer with learning rate `η` and momentum `ρ`.
...
 """
-struct Momentum{T} <: AbstractRule
-  eta::T
-  rho::T
+struct Momentum <: AbstractRule
+  eta::Float64
+  rho::Float64
+  Momentum(η = 0.01, ρ = 0.9) = new(nonneg(η), ρ)
 end
-Momentum(η = 1f-2, ρ = 9f-1) = Momentum{typeof(η)}(η, ρ)
```
[the remark this answers is not in the document]
Comment (CarloLucibello) [reply src/rules.jl:47]: using `@kwdef` would be breaking though, you lose `Momentum(1e-3)`.

File: src/rules.jl (hunk 1 above)
Comment (CarloLucibello) [reply src/rules.jl:53]: > Maybe using eltype(x) would also be fine, and simpler?

I don't see any disadvantage

File: src/rules.jl (hunk 2 above)
[the remark this answers is not in the document]
Comment (mcabbott) [reply src/rules.jl:47]: Oh right, I forgot what defaults it provides. 

We could have our own macro, e.g.
```julia
@def struct Momentum <: AbstractRule
  eta = 0.01
  rho = 0.9
end
```

[the remark this answers is not in the document]
Comment (mcabbott) [reply src/rules.jl]: Done in 3e80095

File: test/runtests.jl [hunk 3]
```diff
@@ -38,12 +38,15 @@ function Optimisers.apply!(o::BiRule, state, x, dx, dx2)
...
 
-# Make Yota's output look like Zygote's:
-
-Yota_gradient(f, xs...) = map(y2z, Base.tail(Yota.grad(f, xs...)[2]))
-y2z(::AbstractZero) = nothing  # we don't care about different flavours of zero
-y2z(t::Tangent) = map(y2z, ChainRulesCore.backing(canonicalize(t)))  # namedtuples!
-y2z(x) = x
+@static if VERSION <= v"1.10-"
+  # In July 2023, Yota works on 1.9 but not nightly (1.11)
+  using Yota
```
Comment (mcabbott) [inline test/runtests.jl:43]: This doesn't prevent an error from Yota not compiling on master. Could revert as it's unrelated to this PR.

File: src/rules.jl [hunk 4]
```diff
@@ -104,20 +108,22 @@ gradients by an estimate their variance, instead of their second moment.
 - Keyword `centred` (or `centered`): Indicates whether to use centred variant
                                      of the algorithm.
 """
-struct RMSProp{T} <: AbstractRule
-  eta::T
-  rho::T
-  epsilon::T
+struct RMSProp <: AbstractRule
+  eta::Float64
```
Comment (mcabbott) [inline src/rules.jl:112]: At present all standardise on Float64. Some chance this should be Float32 instead? I can't really think of when it would make a practical difference.

**Review by mcabbott — COMMENTED** [review]
All rules now changed, and tests pass. The big question is probably whether this counts as a breaking change, or not?

**Comment by darsnack** [comment]
We removed `Descent{T}(…)` type constructors, so unfortunately, yes.

**Comment by mcabbott** [comment]
In fact `Descent{T}` was the one I left, since IIRC someone had a paper doing "gradient descent" with complex learning rate. 

I doubt anyone types that, but the concern is things like BSON, right?

File: src/rules.jl (hunk 4 above)
Comment (mcabbott) [reply src/rules.jl:112]: One quirk of this is that nice Float32 numbers may get printed in a messy way. Fixed in db55e1b now:
```julia
julia> Adam(0.01f0)
Adam(0.009999999776482582, (0.9, 0.999), 1.0e-8)

julia> Adam(0.01f0)  # after db55e1b changes the printing
Adam(0.01, (0.9, 0.999), 1.0e-8)
```

File: Project.toml [hunk 5]
```diff
@@ -1,7 +1,7 @@
 name = "Optimisers"
 uuid = "3bd65402-5787-11e9-1adc-39752487f4e2"
 authors = ["Mike J Innes <mike.j.innes@gmail.com>"]
-version = "0.2.19"
+version = "0.2.20"
```
[the remark this answers is not in the document]
Comment (mcabbott) [reply Project.toml]: [74863b7](https://github.com/FluxML/Optimisers.jl/pull/151/commits/74863b715b651d267867e10500835e5cce443d31) marks it as breaking.

File: src/rules.jl (hunk 4 above)
Comment (mcabbott) [reply src/rules.jl:112]: But produces this, wtf?
```
julia> m = (x = ([1.0], 2.0), y = [3.0]);

julia> s = Optimisers.setup(Momentum(), m)
(x = (Momentum(0.01, 0.9)Leaf(, [0.0]), ()), y = Momentum(0.01, 0.9)Leaf(, [0.0]))
```

File: test/runtests.jl (hunk 3 above)
Comment (CarloLucibello) [reply test/runtests.jl:43]: since this doesn't solve the CI problem let's remove the change from this PR

File: src/rules.jl [hunk 6]
```diff
@@ -470,17 +465,16 @@ Parameters don't need tuning.
...
                          (no need to change default)
 """
-struct NAdam{T} <: AbstractRule
-  eta::T
-  beta::Tuple{T, T}
-  epsilon::T
+@def struct NAdam <: AbstractRule
+  eta = 0.001
+  beta = (0.9, 0.999)
+  epsilon = 1e-8
```
Comment (CarloLucibello) [inline src/rules.jl:471]: the value of epsilon here and in the other optimisers is taken to be 1e-8 as it is also pytorch's choice? 
It mostly used to be
```
julia> eps(Float32)
1.1920929f-7
```
right? I agree with choice by the way.

File: src/rules.jl [hunk 7]
```diff
@@ -260,24 +261,23 @@ end
...
-RAdam(η = 1f-3, β = (9f-1, 9.99f-1), ϵ = eps(typeof(η))) = RAdam{typeof(η)}(η, β, ϵ)
 
 init(o::RAdam, x::AbstractArray) = (zero(x), zero(x), o.beta, 1)
 
-function apply!(o::RAdam, state, x, dx)
-  η, β, ϵ = o.eta, o.beta, o.epsilon
-  ρ∞ = 2/(1-β[2])-1
+function apply!(o::RAdam, state, x::AbstractArray{T}, dx) where T
+  η, β, ϵ = T(o.eta), T.(o.beta), T(o.epsilon)
+  ρ∞ = 2/(1-β[2]) - 1 |> real
```
[the remark this answers is not in the document]
Comment (mcabbott) [reply src/rules.jl:274]: When used with arrays of complex numbers in some tests, `T.(o.beta)` is complex even though beta is real. But if rho is made complex, then `if ρ > 4` fails. It should always have zero imaginary part.

File: src/rules.jl (hunk 6 above)
Comment (mcabbott) [reply src/rules.jl:471]: I think I took this from Flux, so as to minimise the effect of switching:

https://github.com/FluxML/Flux.jl/blob/master/src/optimise/optimisers.jl#L6

File: test/runtests.jl (hunk 3 above)
Comment (mcabbott) [reply test/runtests.jl]: Reverted.

**Review by CarloLucibello — APPROVED** [review]

File: src/rules.jl (hunk 4 above)
Comment (mcabbott) [reply src/rules.jl:112]: Eventually I found the stray `stdout`.

**Comment by mcabbott** [comment]
I merge this now, we can think about whether anything else wants to be ganged into a breaking release.

**Comment by CarloLucibello** [comment]
Tagging a new breaking release now since this fixes a lot of problems and I don't see any breaking change on the horizon.
